version: "3.9"

services:
  backend:
    build: .
    container_name: purplemerit-backend
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - redis
    restart: always

  redis:
    image: redis:7
    container_name: purplemerit-redis
    ports:
      - "6379:6379"
    restart: always
